name: Generate Character Metadata List

on:
  push:
    paths:
      - 'hot_updates/generateCharacterInfoList.js'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force update the metadata'
        required: false
        default: false
        type: boolean
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate CharacterInfoList.json
        working-directory: ./hot_updates
        run: node generateCharacterInfoList.js

      - name: Commit Changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add hot_updates/CharacterInfoList.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update CharacterInfoList.json" && git push)
